### PR TITLE
Minor fixes on the docs

### PR DESCRIPTION
**Pull request by facundofarias**

### CODE REVIEW

**Comment by pavelbucek** [comment]
Hi facundofarias,

thanks for your contribution! We cannot consider merging anything from you unless you sign OCA - Oracle Contributor Agreement, see http://www.oracle.com/technetwork/community/oca-486395.html.

Best regards,
Pavel

**Comment by facundofarias** [comment]
Hi @pavelbucek! 
I will do it now, apologies!

Facundo

**Comment by facundofarias** [comment]
Hi @pavelbucek, I've just received the OCA approbation.
Do you need something else on my side?
Thanks!

**Comment by pavelbucek** [comment]
nope, I'll take care of it.

There was minor change needed - you did not update license header.

**Comment by pavelbucek** [comment]
merged to master and 1.x branches.

Thanks for your contribution!

**Pull request closed without merging**
